--- #YAML:1.0
name:                Bio-Grep
version:             0.10.4
abstract:            Perl extension for searching in DNA and Protein sequences
license:             ~
author:              
    - Markus Riester <mriester@gmx.de>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Bio::AlignIO:                  0
    Bio::Factory::EMBOSS:          0
    Bio::Index::Fasta:             0
    Bio::Root::Root:               0
    Bio::Root::Version:            0
    Bio::Seq:                      0
    Bio::SeqIO:                    0
    Carp::Assert:                  0
    Class::MethodMaker:            2.02
    Getopt::Long:                  2.32
    IO::String:                    1
    IPC::Open3:                    0
    Pod::Usage:                    0
    Readonly:                      0
    ToolSet:                       0.13
    UNIVERSAL::require:            0.11
    version:                       0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
