# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Bio-Grep
version:      v0.0.3
version_from: lib/Bio/Grep.pm
installdirs:  site
requires:
    Class::MethodMaker:            2.02
    Getopt::Long:                  2.32
    IO::String:                    1
    Pod::Usage:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
